Clecs Documentation
===================
Atamert Ölçgen
2.0.x
:toc: left
:numbered:
:source-highlighter: pygments
:pygments-style: friendly

Entity-component-system for Clojure.


image:https://travis-ci.org/muhuk/clecs.svg?branch=master["Build Status", link=https://travis-ci.org/muhuk/clecs]


Latest Release
--------------

Leiningen
~~~~~~~~~

Add this to your `:dependencies` in `project.clj`:

image:http://clojars.org/clecs/latest-version.svg["Clojars Project", link=http://clojars.org/clecs]


Usage
-----

TODO: Fill this in.


Examples
--------

Official demos are link:https://github.com/muhuk/clecs-examples[here].


API Documentation
-----------------

API documentation is link:http://clecs.muhuk.com/2.0.x/api/[here].


Changelog
---------

.Changes Since Version 1.1.x

* `ITransactableWorld` and transaction concept are removed.
+
[source, Clojure]
----
;; A systems process used to call transaction!
;; to get an editable world:
(comment
  (fn [w dt]
    (transaction! w (fn [w] (set-component! w ...))))

;; Now process receives an editable world and can modify
;; the world directly:
(fn [w dt]
  (set-component! w ...))
----

* Components and systems are registered with worlds during
initialization. Use `clecs.world/world` to create a new world.

** `clecs.backend.atom-world/make-world` is removed. Use
`clecs.world/world` with
`clecs.world.backend.atom-world/atom-world-factory` instead:
+
[source, Clojure]
----
(world atom-world-factory
       {:components [(component ...)
                     (component ...)
                     (component ...)
                     ...]
        :initializer (fn [w] ...)
        :systems [...]})
----

** `ISystemManager` is renamed as `IWorld`.
+
Following functions are removed from this protocol:

*** `remove-system!`

*** `set-system!`

*** `systems`

* `world/set-component` accepts entity-id and component type explicitly.
+
[source, Clojure]
----
;; Old way:
(comment
  (def c (->SomeComponent eid x y))
  (world/set-component w c))

;; New way:
(world/set-component w eid :my.ns/SomeComponent {:x x :y y})
----

* `world/set-component` validates its input.

* Queries are constructed using component type keywords instead
of records:
+
[source, Clojure]
----
;; Old way:
(comment
  (defrecord SomeComponent [eid])
  (def q (all SomeComponent)))

;; New way:
(def q (all :my.ns/SomeComponent))
----

* `clecs.core/make-world` is removed.

* Following deprecated functions are removed:

** `clecs.component/component?`

** `clecs.component/component-label`

** `clecs.component/component-type?`

** `clecs.component/defcomponent`

* Removed support for systems as functions.

* Deprecated `IComponent` is removed.


.Changes Since Version 1.0.x

* Components are no longer records. The same API still works but since
a java class is not generated anymore you are likely to get an error
like:
+
[source, Java]
----
java.lang.ClassNotFoundException: java_path.to.YourComponent
----
+
To solve this problem declare components in a `:require` instead
of `:import`. (Examples:
link:https://github.com/muhuk/clecs-examples/commit/a965ab138b888d3137742aa290be87d9e1528bd1[muhuk/clecs-examples@a965ab1]
& link:https://github.com/muhuk/clecs-examples/commit/22de34f592ca6cf3609e0822b9fd2ce6bf30afd0[muhuk/clecs-examples@22de34f])

* Added suport for systems as maps. Assuming `sys-fn` is an old
style system you can write a system as:
+
[source, Clojure]
----
{:process sys-fn}
----


.Changes Since Version 0.2.x

* Replaced function based queries with data driven queries. See `clecs.query`.


Previous Versions
-----------------

* link:http://clecs.muhuk.com/1.1.x/user_guide/[v1.1.x]


See Also
--------

* link:http://gamadu.com/artemis/[Artemis]
* link:https://github.com/markmandel/brute[brute]
* link:https://bitbucket.org/mludwig/entreri/overview[entreri]


License
-------

Copyright (C) 2015 Atamert Ölçgen

This program is distributed under GNU GPL v3 license. See `LICENSE` file.
